/* eslint-disable no-dupe-keys */
export let emojiDB = {
      "⛰️": "Mountain",
      "🌋": "Volcano",
      "🏕️": "Camping",
      "🏖️": "Beach with Umbrella",
      "🏜️": "Desert",
      "🏝️": "Desert Island",
      "🏞️": "National Park",
      "🏟️": "Stadium",
      "🏗️": "Building Construction Hut",
      "🏠": "House",
      "🏢": "Office Building",
      "🏤": "Post Office",
      "🏥": "Hospital",
      "🏦": "Bank",
      "🏨": "Hotel",
      "⛺": "Tent",
      "🌃": "Night with Stars",
      "🌄": "Sunrise Over Mountains",
      "🌅": "Sunrise",
      "🍇": "Grapes",
      "🍈": "Melon",
      "🍉": "Watermelon",
      "🍊": "Tangerine",
      "🍋": "Lemon",
      "🍌": "Banana",
      "🍍": "Pineapple",
      "🥭": "Mango",
      "🍎": "Red Apple",
      "🍏": "Green Apple",
      "🍐": "Pear",
      "🍑": "Peach",
      "🍒": "Cherries",
      "🍓": "Strawberry",
      "🥒": "Cucumber",
      "🥬": "Leafy Green",
      "🥦": "Broccoli",
      "🧄": "Garlic",
      "🧅": "Onion",
      "🍄": "Mushroom",
      "🥜": "Peanuts",
      "🌰": "Chestnut",
      "🍞": "Bread",
      "🥐": "Croissant",
      "🥖": "Baguette Bread",
        "🙈": "See-No-Evil Monkey",
        "🙉️": "Hear-No-Evil Monkey",
        "🙊": "Speak-No-Evil Monkey",
        "🐵": "Monkey Face",
        "🐒": "Monkey",
        "🦍": "Gorilla",
        "🦧": "Orangutan",
        "🐶": "Dog Face",
        "🐕": "Dog",
        "🐩": "Poodle",
        "🐺": "Wolf",
        "🦊": "Fox",
        "🦝": "Raccon",
        "🐱": "Cat Face",
        "🦁": "Lion",
        "🐯": "Tiger Face",
        "🐅": "Tiger",
        "🐆": "Leopard",
        "🐴": "Horse Face",
        "🐎": "Horse",
        "🦄": "Unicorn",
        "🐪": "Camel",
        "🐫": "Two-Hump Camel",
        "🐉" : "Dragon",
        "🐐": "Goat",
        "🐌": "Snail",
        "🐪": "Camel",
        "🐫": "Two-Hump Camel",
        "🦙": "Llama",
        "🐝": "Honeybee",
        "🦒": "Giraffe",
        "🐘": "Elephant",
        "🦏": "Rhinoceros",
        "🦛": "Hippopotamus",
        "🐇": "Rabbit",
        "🦘": "Kangaroo",
        "🐨": "Koala",
        "🐼": "Panda",
      
   
  };
  