/* eslint-disable no-dupe-keys */
export let emojiDB = {

        "🙈": "See-No-Evil Monkey",
        "🙉️": "Hear-No-Evil Monkey",
        "🙊": "Speak-No-Evil Monkey",
        "🐵": "Monkey Face",
        "🐒": "Monkey",
        "🦍": "Gorilla",
        "🦧": "Orangutan",
        "🐶": "Dog Face",
        "🐕": "Dog",
        "🐩": "Poodle",
        "🐺": "Wolf",
        "🦊": "Fox",
        "🦝": "Raccon",
        "🐱": "Cat Face",
        "🦁": "Lion",
        "🐯": "Tiger Face",
        "🐅": "Tiger",
        "🐆": "Leopard",
        "🐴": "Horse Face",
        "🐎": "Horse",
        "🦄": "Unicorn",
        "🦓": "Zebra",
        "🐮": "Cow Face",
        "🐂": "Ox",
        "🐃": "Water Buffalo",
        "🐄": "Cow",
        "🐷": "Pig Face",
        "🐖": "Pig",
        "🐗": "Boar",
        "🐽": "Pig Nose",
        "🐏": "Ram",
        "🐑": "Ewe",
        "🐐": "Goat",
        "🐪": "Camel",
        "🐫": "Two-Hump Camel",
        "🐉" : "Dragon",
        "🦦": "Otter",
        "🐺": "Wolf",
        "🐈": "Cat",
        "🦁": "Lion",
        "🐆": "Leopard",
        "🐅": "Tiger",
        "🐡": "Blowfish",
        "🦂": "Scorpion",
        "🕷️": "Spider",
        "🐋": "Whale",
        "🐸": "Frog",
        "🦉": "Owl",
        "🐟": "Fish",
        "🦈": "Shark",
        "🐬": "Dolphin",
        "🐙": "Octopus",
        "🦇": "Bat",
        "🐻": "Bear",
        "🐧": "Penguin",
        "🐊": "Crocodile",
        "🦅": "Eagle",
        "🐢": "Turtle",
        "🦎": "Lizard",
        "🐍": "Snake",
        "🦍": "Gorilla",
        "🐎": "Horse",
        "🦄": "Unicorn",
        "🕊️": "Dove",
        "🦖": "T-Rex",
        "🦕": "Sauropod",
        "🦓": "Zebra",
        "🦌": "Deer",
        "🐄": "Cow",
        "🐃": "Water Buffalo",
        "🐂": "Ox",
        "🐑 ": "Ewe",
        "🐐": "Goat",
        "🐌": "Snail",
        "🐪": "Camel",
        "🐫": "Two-Hump Camel",
        "🦙": "Llama",
        "🐝": "Honeybee",
        "🦒": "Giraffe",
        "🐘": "Elephant",
        "🦏": "Rhinoceros",
        "🦛": "Hippopotamus",
        "🐇": "Rabbit",
        "🦘": "Kangaroo",
        "🦋": "Butterfly",
        "🐨": "Koala",
        "🐼": "Panda",
        "🐒": "Monkey",
        "🦧": "Orangutan",
        "🐕": "Dog",
        "🦊": "Fox",
        "🦝": "Raccoon",
        "🐗": "Boar",
        "🦗": "Cricket",
        "🐞": "Lady Beetle",
        "🐿️": "Chipmunk",
        "🐜": "Ant",
        "🐁": "Mouse",
        "🐀": "Rat",
        "🦔": "Hedgehog",
        "🐹": "Hamster",
        "🐠": "Tropical Fish",
        "🐛": "Bug",
        "🦚": "Peacock",
        "🦜": "Parrot",
        "🐔": "Chicken",
        "🦨": "Skunk",
        "🦡": "Badger",
        "🦆": "Duck",
        "🦥": "Sloth",
        "🐦": "Bird",
        "🦃": "Turkey",
        "🦢": "Swan",
        "🦩": "Flamingo"
   
  };
  